// <auto-generated />
using ConsoleAppTestes;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ConsoleAppTestes.Migrations
{
    [DbContext(typeof(DesafioDbContexto))]
    [Migration("20190720033128_DesafioDBInicial")]
    partial class DesafioDBInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Desafio.Repositorio.Abstrato.Entidades.Endereco", b =>
                {
                    b.Property<int>("EnderecoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<int>("CEP");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Municipio");

                    b.Property<int>("Numero");

                    b.Property<string>("UF");

                    b.Property<int>("UsuarioId");

                    b.HasKey("EnderecoId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("Desafio.Repositorio.Abstrato.Entidades.Telefone", b =>
                {
                    b.Property<int>("TelefoneId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Numero");

                    b.Property<string>("Tipo");

                    b.Property<int>("UsuarioId");

                    b.HasKey("TelefoneId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Telefones");
                });

            modelBuilder.Entity("Desafio.Repositorio.Abstrato.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("CPF");

                    b.Property<string>("Nome");

                    b.Property<long>("RG");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Desafio.Repositorio.Abstrato.Entidades.Endereco", b =>
                {
                    b.HasOne("Desafio.Repositorio.Abstrato.Entidades.Usuario", "Usuario")
                        .WithOne("Endereco")
                        .HasForeignKey("Desafio.Repositorio.Abstrato.Entidades.Endereco", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Desafio.Repositorio.Abstrato.Entidades.Telefone", b =>
                {
                    b.HasOne("Desafio.Repositorio.Abstrato.Entidades.Usuario", "Usuario")
                        .WithMany("Telefones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
